server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/searchlog/(tree|flame|stats|events)$ {
        default_type application/json;
        add_header Cache-Control "public, max-age=300";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
